# github https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-auth-context.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-viewer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-viewer
  template:
    metadata:
      labels:
        app: kafka-ui-viewer
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:v0.7.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "kafka-cluster"
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
          - name: KAFKA_CLUSTERS_0_METRICS_PORT
            value: "9404"
          - name: AUTH_TYPE
            value: "DISABLED"
          - name: KAFKA_CLUSTERS_0_READONLY
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-viewer
  namespace: kafka
spec:
  selector:
    app: kafka-ui-viewer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
